### PR TITLE
Migrate hi locale

### PR DESCRIPTION
**Pull request by minitesh**
This PR if for issue date-fns/date-fns-typescriptify#176

Fixes https://github.com/date-fns/date-fns-typescriptify/issues/176

### CODE REVIEW

**Review by tan75 — APPROVED** [review]
Thank you for this PR!

**Comment by fturmel** [comment]
Hi everyone, I think this PR might've been merged too quickly.

@minitesh Would you be able to fix the type errors? You can use the `en-US` locale as a reference. When I add the missing `Locale` type in the index, things are flaring up quite a bit.

Screen Shot 2021-12-13 at 10 24 50 AM

**Comment by fturmel** [comment]
(side note, TS linting and some sort of CI integration to verify type issues should really be improved in the project)

**Comment by fturmel** [comment]
I started working on a PR to fix these problems #2845, please join me there

**Pull request merged**
