### PR TITLE
Prepare en-CA locale for release

### PR DESCRIPTION
**Pull request by mimperatore**
This library is great!

@markowsiak Thanks for adding the en-CA locale support! 

This PR intends to help prepare en-CA for inclusion in the next release.

This PR:
- adds to release/contribution docs (giving attribution to @markowsiak for the feature)
- fixes what I believe was error in how "1 second" should be described (https://github.com/date-fns/date-fns/commit/166e0117d23ea364bd6184f28fbfa26ecc8c5957)
- does the exports so this locale is accessible

Hope this helps.  Let me know if you'd like to see some further tweaks or changes.

cc: @leshakoss

### CODE REVIEW

**Comment by mimperatore** [comment]
Looks like `master` isn't building.  There are references to the `ua` locale, but there is no `locale/ua/` folder at all.
```
$ git grep 'ua/index'
src/esm/locale/index.js:export {default as ua} from './ua/index.js'
src/locale/index.js:  ua: require('./ua/index.js'),
typings.d.ts:declare module 'date-fns/locale/ua/index' {
typings.d.ts:declare module 'date-fns/locale/ua/index.js' {
typings.d.ts:declare module 'date-fns/esm/locale/ua/index' {
typings.d.ts:declare module 'date-fns/esm/locale/ua/index.js' {
```

If someone can get master to build, I can rebase my changes.  LMK.

**Comment by markowsiak** [comment]
@mimperatore I actually took the 'a few seconds' edit from what moment uses for consistency between packages.  It reads properly to me as a Canadian, but not sure if there's an "official" stance on it somewhere?

**Comment by mimperatore** [comment]
@markowsiak: fair comment about `moment`, though the `us-EN` locale in this package specifies `1 second` (https://github.com/date-fns/date-fns/blob/0d0b9437005026cf0b79126e068f5f6c0b050446/src/locale/en-US/_lib/formatDistance/index.js#L8), so this makes it a bit more consistent.

**Comment by leshakoss** [comment]
@mimperatore thanks a lot for your contribution! ⭐️ We have updated the locale API again, so the locale has needed some more changes. I cherry-picked still relevant commits and continued your work on this locale here: #714

**Pull request closed without merging**
