### PR TITLE
Add West Frisian (fy) support

### PR DESCRIPTION
**Pull request by damon02**
This adds the [West Frisian language](https://en.wikipedia.org/wiki/West_Frisian_language) spoken in the North of the Netherlands to date-fns.

### CODE REVIEW

**Comment by damon02** [comment]
Hmm no activity here yet, let me explain how and what I based this PR on 😄 

For this pull request I worked together with the Provincie Fryslân (where the language is spoken) and had somebody translate and help me put this translation together. I have direct contacts with people at the province through my company, which we use this library for. 

I also cross checked this with https://unicode.org/cldr/cldr-aux/charts/32/summary/fy.html#1882 and it seems to match, although that page actually has some words in Dutch and not in Frisian, where the PR has these translated correctly.

I didn't see the PR checklist when creating my PR but when browsing at others it seemed missing so, here you go:

----

# PR Checklist
### To maintain `date-fns` top quality, please check if PR fulfills the main contributing requirements:
[x] PR follows style guides specified on the guideline: [Contributing Guide](https://github.com/date-fns/date-fns/blob/master/CONTRIBUTING.md)
[x] Tests for the changes have been added (for bug fixes / features)
[x] Docs have been added / updated (for bug fixes / features)
[ ] Any changes made on the changelog.
[ ] Any changes made on the library version.
[x] Prior to sending pull request FP functions, typings and indices were rebuilt.

#### What is the new behavior?
With this PR, [date-fns](https://date-fns.org) will start to support the Frisian (fy) language.

#### Does this PR introduce a breaking change?
```
* [ ] Yes
* [x] No
```

**Comment by tan75** [comment]
hi @damon02 
Apologies for the delay! could you please resolve the conflicts, then  run `yarn locale-snapshots` again (just in case) and push up your code?

**Comment by damon02** [comment]
> hi @damon02
> Apologies for the delay! could you please resolve the conflicts, then run `yarn locale-snapshots` again (just in case) and push up your code?

I resolved the conflicts by making the PR up to date again with the upstream `master` branch and re-ran the `yarn locale-snapshots` command and pushed this.

**Review by tan75 — APPROVED** [review]
Thank you for this PR! 🙏

**Pull request merged**
