### PR TITLE
Changed scripts bangs to work without having `ts-node` installed globally

### PR DESCRIPTION
**Pull request by JuanM04**

### CODE REVIEW

**Review by fturmel — APPROVED** [review]
Good catch! I didn't even realize I had `ts-node` installed globally.

**Comment by blimmer** [comment]
Sounds good! I think this PR might be preferred to the shebang since it's handles different yarn binary paths transparently.

**Comment by fturmel** [comment]
Thoughts on making the shebang `#!/usr/bin/env yarn ts-node` instead?

**Comment by JuanM04** [comment]
I think the shebang works even if you are using NPM (not confirmed)

**Comment by fturmel** [comment]
`npm` and `pnpm` use a `.bin` directory too, same path.

**Comment by fturmel** [comment]
Looks like a fix for this issue snuck into #3069 and got merged already

**Pull request closed without merging**
