### PR TITLE
add setGlobalLocale

### PR DESCRIPTION
**Pull request by SneakyFish5**
Closes https://github.com/date-fns/date-fns/issues/816

When trying to run the build script, I ran into this error:
```
  const returns = getType(content.returns[0].type.names)
                                         ^

TypeError: Cannot read property '0' of undefined
```

Please let me know if any changes are required

### CODE REVIEW

**Comment by kossnocorp** [comment]
Hey! Thank you a lot for the PR! I'm going to evaluate the PR on the week and help with the build issue.

**Comment by amoerie** [comment]
We are also interested in this change. To give some more context: react-datepicker already implements its own form of "default locale", see https://github.com/Hacker0x01/react-datepicker#localization

I would also suggest a few changes to this PR:

- Rename setGlobalLocale to setDefaultLocale. This makes it explicit that passing a locale in the options overrides the default one. 
- Don't pollute the window / global scope, but use a function closure to save the current default locale. There must be some initialization function where this can be stored.

**Comment by liegeandlief** [comment]
Is this still active? Global locale support would be really useful!

**Comment by hornta** [comment]
I want this feature as well. @SneakyFish5 Have you had time to check up on this more or do you want to hand over it to someone?

**Comment by SneakyFish5** [comment]
Hey, sorry for the late reply. Yea, I don't think I can keep up with this PR anymore, I think I'll go ahead and close it and if someone wants to retake it up, be my guest.

**Comment by Nuboskill** [comment]
@SneakyFish5 Why have you closed this PR? It is very important feature.

**Comment by olee** [comment]
Same thought here - this would be such a simple improvement, but would give a huge benefit.
This is the only thing which really annoys me with date-fns.

**Comment by jdriesen** [comment]
Same here...

**Pull request closed without merging**
