### PR TITLE
Fix Dutch locale - short month name

### PR DESCRIPTION
**Pull request by edorivai**

### CODE REVIEW

**Comment by edorivai** [comment]
Uh, that failing test is not because of my PR, is it?

**Comment by MBing** [comment]
No, we're looking into it. ;)

**Comment by benmccann** [comment]
@edorivai if you rebase onto the latest master the tests should pass now

**Comment by edorivai** [comment]
@benmccann done

**Comment by Alexxzz** [comment]
Shouldn't short name for March be `mrt` in Dutch?
https://en.wikipedia.org/wiki/Date_and_time_notation_in_the_Netherlands
https://nl.wikipedia.org/wiki/Datum_(dagtekening)

**Comment by edorivai** [comment]
@Alexxzz Seems you're right. Updated!

**Pull request merged**
