### PR TITLE
`roundToNearestMinutes` fixes and improvements

### LINKED ISSUE #3129: roundToNearestMinutes roundingMethod producing unexpected results
When using `roundToNearestMinutes` function the rounding method doesn't seem to produce an expected result, or maybe there is something I'm missing.

For Example
`const result = roundToNearestMinutes(new Date(2022, 6, 24, 0, 28, 59), {
  nearestTo: 1,
  roundingMethod: "floor"
});
console.log(result);`

Produces
Sun Jul 24 2022 00:29:00 GMT+0800 (Singapore Standard Time)
Expected
Sun Jul 24 2022 00:28:00 GMT+0800 (Singapore Standard Time)

`const result = roundToNearestMinutes(new Date(2022, 6, 24, 0, 28, 59), {
  nearestTo: 1,
  roundingMethod: "ceil"
});
console.log(result);`

Produces
Sun Jul 24 2022 00:30:00 GMT+0800 (Singapore Standard Time)
Expected
Sun Jul 24 2022 00:29:00 GMT+0800 (Singapore Standard Time)

### PR DESCRIPTION
**Pull request by fturmel**
Closes #3129

The recent addition of the `roundingMethod` option (#3091) was not implemented correctly, and some unit tests were not checking for the right behavior. This PR fixes the problems, adds several unit tests, improves the JS docs and adds two additional examples.

I've also internally renamed the `getRoundingMethod` file and made the function as a default export for consistency to match other functions in the library.

### CODE REVIEW

**Comment by fturmel** [comment]
@im28 Would you mind reviewing the PR, especially the unit tests to make sure everything checks out and there are no missing edge cases?

**Review by im28 — APPROVED** [review]
Looks good to me, Thanks a lot!

**Comment by fturmel** [comment]
Just pushed an update to cover an edge case with `ceil` and milliseconds.

**Comment by MrSuttonmann** [comment]
Hi, would someone be able to fix these merge conflicts so this can be released? I'm relying on this fix for a development! Thanks :)

**Comment by fturmel** [comment]
It seems like `main` has become the working branch for pre-released v3 since I opened this, which explains all the conflicts.

@leshakoss @tan75 I'm going to wait for you to chime in before changing anything. If you want to accept the PR, let me know if you want to merge into the `v2` branch instead, or if I should get rid of the conflicts against `main`.

Obviously the fixes in this PR should find their way to both v2 and upcoming v3.

**Comment by Miyagee** [comment]
Any updates on this PR?

**Comment by grifotv** [comment]
While this PR hasn't been merged, I'm using this simple custom solution https://stackoverflow.com/a/10789415

**Comment by yannbolliger** [comment]
Would also appreciate this being merged.

**Pull request merged**
