### PR TITLE
Make index.js work with system.js

### PR DESCRIPTION
**Pull request by mattlewis92**

### CODE REVIEW

**Comment by mattlewis92** [comment]
@kossnocorp ah I didn't see that, should be fixed now! :)

**Comment by kossnocorp** [comment]
Great, thank you a lot! Going to release a new version ASAP

**Comment by mattlewis92** [comment]
Fantastic, thanks so much for the quick response! :)

**Comment by kossnocorp** [comment]
Your PR was released as `date-fns@1.9.0`, please check if it works as expected.

**Comment by mattlewis92** [comment]
It worked perfectly, thanks a lot!

**Comment by kossnocorp** [comment]
Great! Thank **you** for the contribution!

**Pull request merged**
