### PR TITLE
CS locale now using time seconds, not arc seconds

### LINKED ISSUE #1488: Incorrect Czech translation
The translation for _seconds_ in Czech locale is not correct. It should be “sekunda” (correct unit of time) and its inflections whereas “vteřina” (colloquial, however, an angular unit in reality) is used at the moment.

Was there any strong reasoning behind that @JozefBiros?

https://github.com/date-fns/date-fns/blob/v2.5.1/src/locale/cs/_lib/formatDistance/index.js#L4

### PR DESCRIPTION
**Pull request by march08**
Hey guys, just noticed there is bad wording used for CS locale

Currently word `vteřina` is being used, HOWEVER. Vteřina is a word for arc second, not time second.
For time second, `sekunda` is the correct word to use

See: https://cs.wikipedia.org/wiki/Vte%C5%99ina

edit:
resolves #1488

### CODE REVIEW

**Comment by march08** [comment]
Anyone here who can help with the review?

**Comment by tan75** [comment]
hi @march08 
Apologies for the delay!
The changes you made in your PR seem to be correct however I cant submit Github actions jobs for some reason as it is giving me an error - I am not sure what is going on.
As well, I noticed you didn't commit a new locale snapshot.
Could you please run from the command line `yarn locale-snapshots` and push up the results (`snapshot.md` file)?
This new commit might trigger the GH workflow again so I would be able to approve this PR.
Many thanks!

**Review by tan75 — CHANGES_REQUESTED** [review]
Please push up a locale snapshot

**Comment by leshakoss** [comment]
Hi, thanks a lot for your PR! We merged this fix in #2577

**Pull request closed without merging**
