### PR TITLE
Migate code-base to Typescript using ts-migrate

### PR DESCRIPTION
**Pull request by opudalo**
[ts-migrate](https://github.com/airbnb/ts-migrate/tree/master/packages/ts-migrate) is a CLI tool from Airbnb to help migrate large codebases from JS to TypeScript all in once. 

It runs codemod helpers with a single purpose - to transform JS into compilable TypeScript. It is not ideal, does not guesses all the types correctly, but serves as a good migration starter from JS to TS.

[More on ts-migrate](https://medium.com/airbnb-engineering/ts-migrate-a-tool-for-migrating-to-typescript-at-scale-cd23bfeb5cc).

This PR is an experiment and is WIP, mostly to check if ts-migrate can be used as a migration strategy inline with [Migrate to TypeScript](https://github.com/date-fns/date-fns/discussions/1932) discussion.

Status
- [x] /src/* transformed
- [x] `yarn test` runs succesfully
- [ ] fix `yarn benchmark`
- [x] fix `./scripts/build/build.sh`
- [x] fix `./scripts/build/package.sh`

Renaming is a separate commit, for an easier audit of transformations.

### CODE REVIEW

**Review by kossnocorp — CHANGES_REQUESTED** [review]
Hey, thank you a lot for that! This will drastically speed up the migration and help us a lot!

However, I can't accept this PR as is, even after fixing the issues listed in the TODO list.

1. The first problem is that I am obliged to review every change, and it will take a lot of time and effort.
2. Secondly, the current git changes remove files and create new ones. This will wipe out the whole history and also break all PRs.

Given that, please rollback all the transformations, leave only fixes that ensure that everything works (i.e., build system updates) and provide instructions on how I can locally apply `ts-migrate`, which I will perform myself after we merge the PR.

I realize that you still want to fix the scripts and `yarn benchmark`, and to do that, you need the transformations, so please rollback the transformations at the end.

Please tell me if you need any help!

**Comment by opudalo** [comment]
@kossnocorp yeah, no problem. This PR wasn't meant to be merge at all. Was just experimenting with ts-migrate. It worked pretty good, lol.

**Comment by kossnocorp** [comment]
@opudalo awesome, looking forward!

**Comment by opudalo** [comment]
@kossnocorp I've reverted all transformations/file renaming. 
But this won't compile right now (tests, build scripts won't pass). 
Instead of trying to make Schrodinger tsification (merge only builder parts and support both TS/JS states) I suggest you to take over this PR and finish it. I've added helper scripts so you can migrate code yourself. 

Proposed todo:

1. `yarn ts-migrate:rename-all` Will rename .js → .ts files in `src/*` directory. `ts-migrate` has no way to specify directory to apply renaming, so it does `./*` and then its manually removing renames except in `src` and reverts to git state (run and you'll see)
2. `yarn ts-migrate:migrate` will migrate all files in `src/*` to TypeScript. It mostly adds "@ts-expect-error", so it will compile, but it is mote true migration.
3. fix `yarn benchmark` (for some reason it won't work for me in master too.
4. review everything and marge to master PR with both builder and applied transformations together.

Let me know if I can help with any, but this should be straightforward. As its major change, also it would make sense to create manual test checklist to double check everything. I can't help creating it, as I'm not that aware in lib internals, so that's on you.
However, I can help with testing stuff.

👍

**Comment by kossnocorp** [comment]
Amazing, the plans sound great! I'm on it!

**Comment by kossnocorp** [comment]
@opudalo I finally got to tinkering with the PR. I'm not sure if I want to merge the current result of `ts-migrate` as it doesn't do anything except adding `@ts-ignore`. Right now the migration is easy to track (if it's `.js`, we should migrate it), but with all files named `.ts` it would be more challenging.

I tried to apply [recently added JSDoc plugin](https://github.com/airbnb/ts-migrate/pull/43) but couldn't make it do anything at all. With the result of the plugin, it would be much more valuable.

Could you please try to help me make it work? Here's my script that I experimented with: https://gist.github.com/kossnocorp/9afa7e3cad0e1f5966fc985dde16fed2 (the plugin still not released, so I downloaded the source code locally).

I'm rolling back the transformations and rename for clean diff.

**Comment by opudalo** [comment]
@kossnocorp, guys published a new version it has jsdoc plugin.

However, we have another problem. In most files params are prefixed with "dirty". Thus, have to a) fix naming in codebase and align jsdoc `@params` and function arg names or b) tweak jsdoc plugin to make it handle "dirty" prefix in the name. It's a hack but it will work. 

What do you think? 

image


image

**Comment by leshakoss** [comment]
Closing this because the library is nearly completely typescriptified now

**Pull request closed without merging**
