### PR TITLE
Fix grammar in formatDistance of Ukrainian locale

### PR DESCRIPTION
**Pull request by leshakoss**

### CODE REVIEW

**Comment by leshakoss** [comment]
Trying to address #3170 (I don't speak the language)  @alinkedd @date-fns/i18n-uk could you please verify grammar?

**Comment by alexgul1** [comment]
> @leshakoss looks good for me 👍

the same

**Comment by leshakoss** [comment]
@korzhyk @alexgul1 thanks a lot!

**Comment by alinkedd** [comment]
@leshakoss thank you so much for the PR, I would not hope someone will release a fix so fast.

And sorry that I'm a bit late for this suggestion - I found it a bit confusing to have plural nominative form in singular genitive field for x distances though it fixes everything 😅. imho, rewriting declension function (which is almost identical to ru and be locales and caused the problem) is more approriate way here, so we don't change library approach. I know that that would make function more complicated, but could not leave it without a few words in comment at least.

Thanks again for your work!

**Pull request merged**
