### PR TITLE
Added flow types for every function

### PR DESCRIPTION
**Pull request by JohnyDays**
Added a .js.flow file for each function describing their inputs/outputs.
Added flow headers to every test file, so i could verify they were correct
All test files pass flow checks correctly!
This doesn't change behaviour so every test and build step passes / remains unchanged.

PS: If you're not familiar with flow, I can give some more context or examples of the typechecking

### CODE REVIEW

**Comment by kossnocorp** [comment]
@JohnyDays great stuff, thank you a lot! I'm familiar with flow but I need some time to play with PR. Also, it makes sense to add flow check to CI to make sure that it will not break in the future.

**Comment by JohnyDays** [comment]
I'm not too familiar with travis, but I think that does the trick

**Comment by kossnocorp** [comment]
@JohnyDays 👍 it does, but now I have problem with SauceLabs.

**Comment by kossnocorp** [comment]
@JohnyDays it turned out that Travis [doesn't expose SauceLabs credentials for security reasons](https://docs.travis-ci.com/user/pull-requests/#Security-Restrictions-when-testing-Pull-Requests). I've [disabled cross-platform tests for external PRs](https://github.com/date-fns/date-fns/pull/206). To make it green, please rebase against master branch.

**Comment by JohnyDays** [comment]
Done 👍

**Comment by kossnocorp** [comment]
@JohnyDays thanks 🙏🏽!

**Comment by JohnyDays** [comment]
Cool 🍒 
Does something have to be done to include these files in the next npm release? release_npm.sh seems to only exlclude test files so I'm guessing these will be there

**Comment by kossnocorp** [comment]
@JohnyDays I will adjust this. 

I have an another problem: I just realied that `// @flow` must be at the first line, otherwise a file going to be ignored:

tmux___users_koss_src_kossnocorp_assets-webpack-plugin

vs

tmux___users_koss_src_kossnocorp_assets-webpack-plugin

I'm not enough experienced with Flow so I can't think of a suitable solution 😞

**Comment by JohnyDays** [comment]
Oh, you're right. I'll submit another PR.

**Comment by kossnocorp** [comment]
@JohnyDays 👍

**Pull request merged**
