### PR TITLE
Fix th locale

### PR DESCRIPTION
**Pull request by hawkup**
มกราคาม to มกราคม

reference:
- https://github.com/moment/moment/blob/develop/locale/th.js
- https://th.wikipedia.org/wiki/%E0%B9%80%E0%B8%94%E0%B8%B7%E0%B8%AD%E0%B8%99

### CODE REVIEW

**Comment by benmccann** [comment]
Confirmed with Google Translate as well

@kossnocorp @leshakoss I found 4 PRs that are all attempting to make this same change and linked the others to this one. Can we merge this one and close the others?

**Comment by benmccann** [comment]
@kossnocorp @leshakoss any reason not to merge this PR?

**Comment by leshakoss** [comment]
@benmccann sorry, I am a little occupied with other stuff right now, I'll probably take a look at it the next week along with other locale PRs

**Comment by leshakoss** [comment]
@benmccann I mean, I looked at it and it is obviously perfect, but there's usually a lot to do after merging locale changes (adding changelog entries and docs stuff) so it is easier to in a bunch. Really sorry for the delay

**Comment by benmccann** [comment]
Thanks!!

**Comment by leshakoss** [comment]
@hawkup @benmccann Thanks a lot for your contribution! I will try to release this as a part of v2.0.0-beta.1 as soon as possible (hopefully a few days). I will let you know when it’s released.

**Pull request merged**
