### PR TITLE
Add Persian locale (fa-IR) for v2

### PR DESCRIPTION
**Pull request by mort3za**
Hey, I have created a new locale. Check it please.
Thank you

### CODE REVIEW

**Comment by mberneti** [comment]
you're welcome

**Comment by kossnocorp** [comment]
I've released the change as `v2.0.0-alpha.29`: https://gist.github.com/kossnocorp/a307a464760b405bb78ef5020a4ab136#v200-alpha29

**Comment by ehsaneona** [comment]
The problem with this Persian version that you added is that it is not the common calendar in Iran and in Iran Jalali (shamsi) mode is common.

**Comment by ehsaneona** [comment]
> you're welcome


The problem with this Persian version that you added is that it is not the common calendar in Iran and in Iran Jalali (shamsi) mode is common.

**Pull request merged**
