### PR TITLE
Add Bengali locale (bn) for v2

### LINKED ISSUE #836: Bengali language support

### PR DESCRIPTION
**Pull request by touhidrahman**
Fixes #836 
This PR will introduce Bengali (bn) locale in date-fns.

### CODE REVIEW

**Comment by sh4hids** [comment]
Thanks for such a nice work. If possible please fix these spells:
বেশী - বেশি
ঘন্টা - ঘণ্টা

**Comment by touhidrahman** [comment]
@sh4hids Thank you for your review comment. AFAIK, bangla Academy prefers ন over ণ nowadays. And with বেশি, I agree with you as Bangla Academy is trying to move from ী to ি as much as possible. However IMO this is a minor issue, let's wait for the merge first. Or you can go ahead and change the বেশী to বেশি।

**Comment by kossnocorp** [comment]
I'm going to go through pending locales and then release a new v2 version. Thank you again, you guys are great!

**Comment by kossnocorp** [comment]
I've just published a new version with this locale `date-fns@2.0.0-alpha.18`. See the change log: https://gist.github.com/kossnocorp/a307a464760b405bb78ef5020a4ab136#v200-alpha18

Thank you again for your work!

**Pull request merged**
