### PR TITLE
Remove dots in `dd` and `ddd` in Polish format locale

### PR DESCRIPTION
**Pull request by justrag**
The dots after weekdays2char and weekdays3char are kinda silly - you can always add them manually if you need them but you cannot remove them. And they're not in any way standard.

### CODE REVIEW

**Comment by leshakoss** [comment]
@date-fns/i18n-polish

**Comment by justrag** [comment]
I revised the tests, too. And fixed "sob" -> "sb" in 2chars.

**Comment by ertrzyiks** [comment]
Actually, there are rules standardizing usage of a dot in shortcuts and one of them says to put dot when the last letter in a shortcut is NOT the last letter of a word. Also you can not add a dot manually only for `pl` locale, you will need to do this for all locales if you decide to have a dot after `dd`.

However, I think it makes sense to remove dots, but for the sake of consistency. I can not find any other locale with a dot here.

**Comment by piotrd** [comment]
I just took a look at how it is handled e.g. in macOS, and in locale preferences I've found the following options for names of days:

image

So as you can see, there is a version of 3-character day shortcuts with and without a dot. Maybe that's the way to go, i.e. introduce 2 new formats: `weekdays2charWithDot` and `weekdays3charWithDot`?

**Comment by leshakoss** [comment]
@ertrzyiks @piotrd `dd` and `ddd` formatters don't have to be exactly 2 and 3 characters, they are just "short" and "shorter" versions of weekdays and can be any number of characters which make more sense in localized formatted date. As for this locale, I suggest using these values (which I randomly found on internet): http://www.unicode.org/cldr/charts/29/summary/pl.html#1825 http://www.unicode.org/cldr/charts/29/summary/pl.html#1839 I don't know how much is this a standard of some sort or anything so maybe I am wrong on this

**Comment by justrag** [comment]
Actually, the version I'm interested in most is the one I commonly see in the wall calendars: pn wt śr cz pt sb nd. Short and to the point.

**Comment by piotrd** [comment]
I have nothing against the proposed format (although wall calendars are no authority to me), but I can imagine someone else coming in a few days and asking to take that back :)

On a more serious side, I value consistency above individual preferences. I took a look at other locale in date-fns (not all, but most of them) and found dots only in french ones (and only in 3char version). So I think the change proposed in this PR is consistent with majority and can be merged.

**Comment by ertrzyiks** [comment]
or, if we take that `dd` is a short symbol and `ddd` is an abbreviation then we can follow french translation and remove dots only from the shortest version. Similar idea is behind unicode.org tables linked by @leshakoss

**Comment by piotrd** [comment]
This way or another, @leshakoss or @kossnocorp should make the decision and IMHO enforce consistency across all locale.

**Comment by leshakoss** [comment]
personal preference < consistency < rules/standards of languages

It's the same issue as with `a`/`A`/`aa` formatters and AM/PM; and with capital first letter of months and weekdays: different languages have different rules and I would prefer `format` to format dates like if native speaker wrote them, as opposed to direct translation of English language locale.

For `dd` (aka `weekdays2char `), calendars sound like a good point of reference (I think `Su`, `Mo`, ..., `Sa` of `en` locale are taken from calendars too)

`ddd` (`weekdays3char`) is supposed to look like an abbreviation in the middle of the text or, for example, in some official document.

It is true that most `date-fns` locales use the same 2- and 3-letter formats for weekdays, but I don't really know how many of those are artifacts of direct translation of English language locale and should be fixed.

**Comment by piotrd** [comment]
If we treat `weekdays2char` as the shortest meaningful format, then I don't see a reason to keep dots in it.

However, for the `weekdays3char`, as @leshakoss suggested, I would stick to version officially acknowledged as correct by Polish language dictionaries - with a dot:

> poniedziałek => pon./ pn. 
wtorek => wt. 
środa => śr. 
czwartek => czw. 
piątek => piąt./ pt. 
sobota => sob. 
niedziela => niedz.

(which also means we have Sunday abbreviated incorrectly in locale)

References: [1](http://portalwiedzy.onet.pl/140198,,,,dni_tygodnia_-_pisownia_skrotow,haslo.html?drukuj=1), [2](http://sjp.pwn.pl/poradnia/haslo/skroty-dni-tygodnia;2315.html), [3](http://www.edupedia.pl/words/index/show/401176_slownik_poprawnej_polszczyzny-dni_tygodnia.html).

> It is true that most date-fns locales use the same 2- and 3-letter formats for weekdays, but I don't really know how many of those are artifacts of direct translation of English language locale and should be fixed.

Good point. I don't know either.

**Comment by justrag** [comment]
Ammended the PR according to discussion.

> var weekdays2char = ['nd', 'pn', 'wt', 'śr', 'cz', 'pt', 'sb']
> var weekdays3char = ['niedz.', 'pon.', 'wt.', 'śr.', 'czw.', 'piąt.', 'sob.']

**Comment by leshakoss** [comment]
@justrag thanks a lot for your contribution and you guys @date-fns/i18n-polish for the discussion! ⭐️ This fix was released as [v1.28.2](https://github.com/date-fns/date-fns/releases/tag/v1.28.2) (diff: https://github.com/date-fns/date-fns/compare/v1.28.1...v1.28.2)

**Comment by justrag** [comment]
You're welcome and thanks for the org invitation :)
(I think my PR actually removes more characters than it adds ;) )

**Pull request merged**
