### PR TITLE
Add nb_NO locale

### LINKED ISSUE #290: Norwegian Bokmål (nb_NO) support
🇳🇴

### PR DESCRIPTION
**Pull request by Hanse**
Add support for [Norwegian Bokmål (nb_NO)](http://lh.2xlibre.net/locale/nb_NO/).

The first day of a week is Monday. Do I need to specify that somewhere?

Closes #290.

### CODE REVIEW

**Comment by LeshaKoss** [comment]
@Hanse Thank you!

> The first day of a week is Monday. Do I need to specify that somewhere?

No, right now `weekStartsOn` isn't a part of locales but a separate option specified in functions independently (it may change in future major versions)

**Comment by LeshaKoss** [comment]
@Hanse please rename it into just `nb`. We [generally](https://github.com/date-fns/date-fns/tree/master/src/locale) use two letter codes for languages (except in cases when a language is a variant of a macrolanguage)

**Comment by Hanse** [comment]
Okay, done!

**Comment by LeshaKoss** [comment]
@Hanse thank you for your contribution! 🇳🇴 Norwegian Bokmål locale was released with [1.14.0](https://github.com/date-fns/date-fns/releases/tag/v1.14.0) and also was broken by me 😅 and fixed in [1.14.1](https://github.com/date-fns/date-fns/releases/tag/v1.14.1). (diff overall: https://github.com/date-fns/date-fns/compare/v1.13.0...v1.14.1)

**Comment by stianlp** [comment]
Looks like there is an issue with the build. In https://github.com/date-fns/date-fns/blob/master/src/locale/nb/_lib/localize/index.js weekdays abbreviated is `['søn', 'man', 'tir', 'ons', 'tor', 'fre', 'lør']`.

When I install date-fns, this is what I find in node_modules. `var weekdays3char = ['sø.', 'ma.', 'ti.', 'on.', 'to.', 'fr.', 'lø.']`. I assume weekdays3char should be the same list as dayValues abbreviated?

So doing `format(date, 'ddd D. MMM', { locale: nb });`, ends up being "Ma. 28. jan", not "Man 28. jan".

**Pull request merged**
