### PR TITLE
Add SR locale

### PR DESCRIPTION
**Pull request by mawi12345**
Add SR (Serbian) language support (#704)

### CODE REVIEW

**Comment by mawi12345** [comment]
Is it possible to trigger Travis again?
https://travis-ci.org/date-fns/date-fns/jobs/356340838 is an timeout error....

**Comment by leshakoss** [comment]
@mawi12345 restarted it

**Comment by kossnocorp** [comment]
I'm sorry that it took so much time to merge it. With v2 in active development, v1 got overlooked. I'm going to ship this PR with the upcoming v1 release. Thank you very much for your work!

**Comment by kossnocorp** [comment]
The locale was released with `v1.30.1`. See: https://blog.date-fns.org/post/v130-is-out-m35nqh4m13r7

Thank you again!

**Pull request merged**
