### PR TITLE
Added isLegitimate

### PR DESCRIPTION
**Pull request by mrenty**
Added a function to check if the passed arguments convert to a date which exists.

`isLegitimate(2018, 0, 31)` returns `true`, while `isLegitimate(2018, 1, 31)` returns `false`.

### CODE REVIEW

**Comment by leshakoss** [comment]
@mrenty we actually had a function like that but it was scrapped because it caused some special cases with FP fns and generally made a lot of trouble. Let me check if you could find it

**Comment by leshakoss** [comment]
@mrenty here it is: https://github.com/date-fns/date-fns/pull/195

**Comment by leshakoss** [comment]
Anyway, the reasons we removed it are still valid, so yeah. I'll take a look at it next week and think about it, but we'll probably close this PR

**Comment by mrenty** [comment]
@leshakoss alright no problem, let me know if you have any other remarks and/or questions 👍

**Pull request merged**
