### PR TITLE
Finalize prettier

### LINKED ISSUE #753: Finalize migration to Prettier
Standard.js is great but Prettier is better.

### PR DESCRIPTION
**Pull request by redbmk**
To make the diffs a little easier to read I made had one commit that just ran `prettier` on the whole repo.

The next commit adds `prettier` to the `lint` script to enforce styling for all js, ts, and json files.

Prettier now runs on pre-commit hooks not just for js files but for ts and json as well.

Fixes #753

### CODE REVIEW

**Comment by kossnocorp** [comment]
Hey, thank you a lot for the effort, but I can't accept this PR. First of all, it's too much of a burden to review every file, which I must do to ensure no security breaches or other sensitive issues. It's much easier for me to run the Prettier myself. Secondly, it will break multiple PRs and add more work for other contributors and me.

**Comment by redbmk** [comment]
@kossnocorp Totally understandable about not trusting the `prettier --write` commit. The reason I included two separate commits was to make review easier. I'd be happy to pull that commit out and let you run it yourself. The real change aside from running `prettier --write` only changes two lines:

```diff
diff --git a/package.json b/package.json
index f4dd1ff1..839c7cc0 100644
--- a/package.json
+++ b/package.json
@@ -21,7 +21,7 @@
   "module": "esm/index.js",
   "scripts": {
     "test": "karma start config/karma.js",
-    "lint": "eslint .",
+    "lint": "eslint . && prettier --check '**/*.{js,ts,json}'",
     "lint-types": "eslint --config=.ts-eslintrc.js typings.d.ts",
     "locale-snapshots": "env TZ=utc babel-node --extensions .ts,.js ./scripts/build/localeSnapshots/index.js",
     "benchmark": "env TEST_BENCHMARK=true yarn test --single-run",
@@ -33,7 +33,7 @@
     }
   },
   "lint-staged": {
-    "*.js": [
+    "*.{js,ts,json}": [
       "prettier --write",
       "git add"
     ]
```

That's a great point though about breaking existing PRs. I can't really think of a good way to close #753 without taking a really long time or waiting until you have very few PRs open.

I think at the very least you could add ts and json to the pre-commit hook, which wouldn't break any existing PRs and would format those files going forward. If you're migrating to ts it seems like you'd want to be formatting those files as well.

**Comment by redbmk** [comment]
@kossnocorp I updated this branch to only have the lint-staged change (without running prettier on the whole codebase the `prettier --check` wouldn't work since that would break everyone's tests).

I feel like that'd be a safe step towards making progress on #753. If you want I could create a new PR or I think you could just reopen this one for it to sync up.

**Comment by kossnocorp** [comment]
@redbmk, thank you for understanding. If you don't mind, could you please open another PR with the lint-staged update and re-open this one with the lint command update? I want to push the first one right now, and the second will have to wait. Thanks!

**Comment by redbmk** [comment]
@kossnocorp OK I just created #2067 with the lint-staged changes and I updated this branch to include just the `lint` command update.

For reference, if at some point you wanted to run through all files with prettier, the command is `prettier --write '**/*.{js,ts,json}'`. One way to speed along the process without being a huge nuisance might be to do that on a few chunks of files at a time if there aren't outstanding PRs for them.

I can't re-open this pull request though. Is that something you're able to do or should I make a new one for this?

**Pull request closed without merging**
