### PR TITLE
remaining locales migration to TypeScript

### PR DESCRIPTION
**Pull request by fturmel**
Let's start the new year with a bang! Hope this isn't too unwieldy, but I opted for one migration per commit (easier reviews) and one PR as to not flood the project with 50+ individual PRs.

I worked with diffs of the `en-US` locale for every single file to try to keep the reference implementation's code shape when possible.

**Overview**

- all remaining locales were migrated to TS except for `fil` which has been broken for a while, and `uk` which already had an approved PR
- fixed a few previously migrated locales that had type issues
- the `nn` and `sv` locales support `options.onlyNumeric` in `formatDistance`, so I added it to the `FormatDistanceOptions` type

**Snapshot.md file changes (6 locales total)**

- Fixed issue parsing months in `hr`, `ka`, `sr` and `sr-Latn`
- Fixed issue parsing day of week in `ka`
- Fixed weeks support in `formatDuration` of `kk`
- I _believe_ I fixed a code issue in the `lt` locale's `formatDistance` that prevented it from using future tense with suffixes. I don't speak the language, so could someone confirm this is OK? Hard-coding [this constant](https://github.com/fturmel/date-fns/blob/b5cddfb54d7a8af59435cbd23339ca02d5534186/src/locale/lt/_lib/formatDistance/index.ts#L161) to `false` reverts to the old behavior. @date-fns/i18n-lt 

fixes https://github.com/date-fns/date-fns-typescriptify/issues/150
fixes https://github.com/date-fns/date-fns-typescriptify/issues/151
fixes https://github.com/date-fns/date-fns-typescriptify/issues/152
fixes https://github.com/date-fns/date-fns-typescriptify/issues/153
fixes https://github.com/date-fns/date-fns-typescriptify/issues/155
fixes https://github.com/date-fns/date-fns-typescriptify/issues/164
fixes https://github.com/date-fns/date-fns-typescriptify/issues/165
fixes https://github.com/date-fns/date-fns-typescriptify/issues/166
fixes https://github.com/date-fns/date-fns-typescriptify/issues/167
fixes https://github.com/date-fns/date-fns-typescriptify/issues/219
fixes https://github.com/date-fns/date-fns-typescriptify/issues/173
fixes https://github.com/date-fns/date-fns-typescriptify/issues/174
fixes https://github.com/date-fns/date-fns-typescriptify/issues/175
fixes https://github.com/date-fns/date-fns-typescriptify/issues/177
fixes https://github.com/date-fns/date-fns-typescriptify/issues/220
fixes https://github.com/date-fns/date-fns-typescriptify/issues/178
fixes https://github.com/date-fns/date-fns-typescriptify/issues/179
fixes https://github.com/date-fns/date-fns-typescriptify/issues/184
fixes https://github.com/date-fns/date-fns-typescriptify/issues/185
fixes https://github.com/date-fns/date-fns-typescriptify/issues/186
fixes https://github.com/date-fns/date-fns-typescriptify/issues/188
fixes https://github.com/date-fns/date-fns-typescriptify/issues/189
fixes https://github.com/date-fns/date-fns-typescriptify/issues/190
fixes https://github.com/date-fns/date-fns-typescriptify/issues/191
fixes https://github.com/date-fns/date-fns-typescriptify/issues/192
fixes https://github.com/date-fns/date-fns-typescriptify/issues/193
fixes https://github.com/date-fns/date-fns-typescriptify/issues/194
fixes https://github.com/date-fns/date-fns-typescriptify/issues/197
fixes https://github.com/date-fns/date-fns-typescriptify/issues/195
fixes https://github.com/date-fns/date-fns-typescriptify/issues/196
fixes https://github.com/date-fns/date-fns-typescriptify/issues/197
fixes https://github.com/date-fns/date-fns-typescriptify/issues/198
fixes https://github.com/date-fns/date-fns-typescriptify/issues/200
fixes https://github.com/date-fns/date-fns-typescriptify/issues/199
fixes https://github.com/date-fns/date-fns-typescriptify/issues/201
fixes https://github.com/date-fns/date-fns-typescriptify/issues/202
fixes https://github.com/date-fns/date-fns-typescriptify/issues/206
fixes https://github.com/date-fns/date-fns-typescriptify/issues/205
fixes https://github.com/date-fns/date-fns-typescriptify/issues/207
fixes https://github.com/date-fns/date-fns-typescriptify/issues/208
fixes https://github.com/date-fns/date-fns-typescriptify/issues/209
fixes https://github.com/date-fns/date-fns-typescriptify/issues/210
fixes https://github.com/date-fns/date-fns-typescriptify/issues/212
fixes https://github.com/date-fns/date-fns-typescriptify/issues/214
fixes https://github.com/date-fns/date-fns-typescriptify/issues/215
fixes https://github.com/date-fns/date-fns-typescriptify/issues/216
fixes https://github.com/date-fns/date-fns-typescriptify/issues/217

### CODE REVIEW

**Comment by tan75** [comment]
hi @date-fns/i18n-lt
could you please have a look into this fix:
https://github.com/fturmel/date-fns/blob/b5cddfb54d7a8af59435cbd23339ca02d5534186/src/locale/lt/_lib/formatDistance/index.ts#L161

**Review by tan75 — APPROVED** [review]
Thank you so much for this impressive work! 🚀 🙏

**Comment by fturmel** [comment]
You're welcome! Thanks for reviewing it so quickly.

**Comment by fturmel** [comment]
@leshakoss `gd` and `sl` were also migrated in this PR, you can close:

https://github.com/date-fns/date-fns-typescriptify/issues/204
https://github.com/date-fns/date-fns-typescriptify/issues/172

**Comment by fturmel** [comment]
@leshakoss also I had migrated `ru` in this PR too, so you can probably close #2895

**Pull request merged**
