### PR TITLE
Fix `sv` locale abbreviated months matcher

### LINKED ISSUE #3133: parse 'd MMM y' date with SV locale returns invalid date
Hi,

it seems that for SV, the parser returns invalid date for 'd MMM y'. Example below tested with v2.29.1.

```
import { format, parse } from "date-fns";
import sv from "date-fns/locale/sv";

const locale = { locale: sv };
const dateIn = new Date("July 3, 2002 03:24:50"); //new Date("June 3, 2002 03:24:50"); throws too
const formatStyle = "d MMM y";
const formatted = format(dateIn, formatStyle, locale); // 3 juli 2002
const parsed = parse(formatted, formatStyle, new Date(), locale); //Invalid Date

```

Any help much appreciated to resolve this.

### PR DESCRIPTION
**Pull request by fturmel**
Closes #3133

This allows `mars`, `juni` and `juli` to be correctly parsed with the `MMM` (abbreviated month) token.

### CODE REVIEW

**Comment by leshakoss** [comment]
@fturmel  hi, could you please change the base branch for this PR from `main` to `v2` and then rebase? I want to ship this as a patch

**Review by leshakoss — APPROVED** [review]
Thanks a lot!

**Comment by fturmel** [comment]
@leshakoss hold on, the rebase wasn't done yet on this PR

**Comment by leshakoss** [comment]
Cherry-picked this PR in #3160 and then released as v2.29.2: https://github.com/date-fns/date-fns/releases/tag/v2.29.2

**Pull request closed without merging**
