### PR TITLE
[tests] add coverage reports

### PR DESCRIPTION
**Pull request by nanomosfet**
References https://github.com/date-fns/date-fns/issues/1079

Note: added resolutions to `package.json` because  currently webpack is facing this build and the build fails. 
* [reference this issue for more details](https://github.com/webpack/webpack/issues/8768)

### CODE REVIEW

**Comment by nanomosfet** [comment]
If you look at the travis build closely the job that is failing is the "Produce coverage" step.

The reason for this is because date-fns/date-fns is not on-boarded to coveralls.

I have reproduced this on my fork except I have on-boarded to coveralls.

You can see the passing build here:
* PR Build
  * https://travis-ci.com/nanomosfet/date-fns/builds/100355248
* merge build
  * https://travis-ci.com/nanomosfet/date-fns/builds/100356001

And the remote coverage reports here:
* https://coveralls.io/github/nanomosfet/date-fns

Also the coverage is going to be collected in <root>/coverage after `yarn test --single-run`

So now we just need the admin(or make me a member 😜 )  of this repo to create an account with coveralls and allow coveralls to access this repository. Then we will have automatic coverage reports for date-fns!

**Comment by nanomosfet** [comment]
@kossnocorp @leshakoss When you get the chance could you review this?

**Comment by kossnocorp** [comment]
Hey, thank you so much for your work! That will be a lovely addition to our test suite. However, there is a problem I want to address before we can merge it. Adding coverage generation to all test runs made the build run 30% slower. I'm closing this PR to continue your work at #1187.

Btw, there's something wrong with the commits ownership, did you remove your xxx@intuit.com from your GitHub profile?

**Comment by nanomosfet** [comment]
@kossnocorp Oh no! I must of done the work on my work laptop!

Anyway we can change the ownership to timmyzsearcy@gmail.com?

**Comment by kossnocorp** [comment]
Done! I had to get my hands dirty and force push to master: https://github.com/date-fns/date-fns/commit/07d0349b98e37b4931d47e48bc4aa3ec12ab2864

**Pull request closed without merging**
