### PR TITLE
feat: add en-CA locale

### PR DESCRIPTION
**Pull request by markowsiak**
Adds locale for English Canada

### CODE REVIEW

**Comment by markowsiak** [comment]
Thanks for checking that @leshakoss ! I've pushed up those changes 👍

**Comment by leshakoss** [comment]
@markowsiak Thanks a lot for your contribution! I will try to release this as a part of v2.0.0-beta.1 as soon as possible (hopefully a few days). I will let you know when it’s released.

**Comment by markowsiak** [comment]
No problem @leshakoss , thanks for the turn around as well 👍 
I hope to add quite a few more locales in the coming weeks.  Is Gitter the best way to keep in contact with you?  Thanks again 💯

**Comment by leshakoss** [comment]
@markowsiak it's best to write directly on my email (it's seen on my github profile). Please keep in mind that some locale API changes coming soon (see #660) but I think I will stabilize the API in a few days. Thanks!

**Pull request merged**
