### PR TITLE
Fix package name

### PR DESCRIPTION
**Pull request by TatiTheFreaK**

### CODE REVIEW

**Comment by kossnocorp** [comment]
You've changed the example for `date-fns-tz`. `date-fns-timezone` example is below.

**Comment by TatiTheFreaK** [comment]
Sorry I didn't explain on the description what I did. (rs)
On the documentation, both examples shows the imported package name as `date-fns-timezone`, but the example I changed, as you said, was for the `date-fns-tz`, so I believe the imported package name on the example is wrong.
Again, sorry I didn't explain at first

**Comment by kossnocorp** [comment]
Oh, I see it know. You're right, sorry I got confused!

**Comment by kossnocorp** [comment]
Thank you for spotting it!

**Pull request merged**
