### PR TITLE
fix CA spelling errors and update following official gramatical rules

### PR DESCRIPTION
**Pull request by avizcaino**
I've updated catalan locale with some gramatical corrections and following official gramatical rules.

### CODE REVIEW

**Comment by avizcaino** [comment]
Seems there is a problem with the `Coverage report` stage on Travis. I reopen #1079 for further investigation.

**Comment by kossnocorp** [comment]
I'll leave it open for some time in case others would have any comments. If there are no comments or everything's fine, I'll merge and ship it later today or this week.

**Comment by avizcaino** [comment]
Great!

**Comment by kossnocorp** [comment]
Thank you again, I've shipped this PR as `v2.0.0-beta.5`

**Pull request merged**
