### PR TITLE
Remove non-standard wordMapping in formatDistance for nn and sv locales

### PR DESCRIPTION
**Pull request by cupofjoakim**
Today norwegian nynorsk (nn) and swedish (sv) replaces numbers under 13 with words. As far as I can tell, they are the only locales that do so. The other big norwegian dialect (nb) does not do it. I tried looking at the git history and it seems the word mapping has been here a long time and just hasn't been questioned.

As a swedish man who grew up on the border to norway, I propose that we leave this behind. I don't find the `formatDistance` behaviour problematic when used in isolation, but considering its' use in `formatDuration`, it gets a bit more iffy:

```ts
// given 
formatDuration(duration, {delimiter: ', ', locale})
// now
// `15 dagar, fyra timmar, tio minuter, 15 sekunder`
// after
// `15 dagar, 4 timmar, 10 minuter, 15 sekunder`
```

Earlier the option `onlyNumeric` existed for sv and nn to bring about this behaviour, but it was undocumented and removed in v3.0.0: https://github.com/date-fns/date-fns/releases/tag/v3.0.0

Addresses #3805 and (i believe) #3188

### CODE REVIEW

**Review by alexandernanberg — APPROVED** [review]
SGTM

**Comment by fturmel** [comment]
> @alexandernanberg @kossnocorp The test failure seems to be due to this line: https://github.com/date-fns/date-fns/blob/main/src/isDate/test.ts#L46
> 
> `it.skip` takes a function, not a string. Changing it to `it.skip(() => "returns true for a date passed from another iframe")` makes the test suite work again.
> 
> Should I commit that here? How do you prefer to work with unrelated changes like this?

That's a weird one... The Vitest types allow this form and it works with Node.

https://github.com/vitest-dev/vitest/blob/70a277b5abc8b5586542adec8de10edb43a3e96f/packages/runner/src/types/tasks.ts#L249-L256

This new behavior (bug?) was introduced in Bun v1.1.11 and emerged because the CI always uses the latest Bun version.

IMO you should create a new PR for your proposed solution since every new PR/commit with make the CI test fail and it should be merged with a high priority. I would tweak it to be `it.skip("returns true for a date passed from another iframe", () => {});` since the string is the test name being skipped and not a return value.

**Comment by cupofjoakim** [comment]
@fturmel I created a PR to fix that issue like you suggested: #3827

**Comment by cupofjoakim** [comment]
Given that the test has been fixed upstream i've closed the other PR.

@kossnocorp What do you think about this change? Is it too big of a change to consider a minor?

**Comment by mheine** [comment]
Any updates on this? Stumbled upon this exact issue not too long ago, and while we've found a workaround, I'd love to just be able to use this instead. Cheers and thanks for your work in any case folks! 🎉

**Comment by wihlke** [comment]
I also just stumbled on this issue. Hoping it gets merged soon!

**Comment by cupofjoakim** [comment]
@kossnocorp Bumping this to get a yay or nay. Happy to close this if it's a bad fit.

**Comment by cupofjoakim** [comment]
@kossnocorp I'll close this by the end of the week unless reviewed, no point in letting it hang around forever.

**Comment by cupofjoakim** [comment]
Ok, closing.

**Comment by wihlke** [comment]
That’s depressing

**Pull request closed without merging**
