### PR TITLE
Add pt-BR locale

### LINKED ISSUE #582: pt-BR locale
Letting people know I intend to start working on it

### PR DESCRIPTION
**Pull request by duailibe**
Fixes #582

I decided not to reuse the `pt` locale because it's not ready for v2 and I wasn't comfortable changing it

### CODE REVIEW

**Comment by melonmanchan** [comment]
@leshakoss What's the status here? Can this be merged already? 🙂

**Comment by VitaliiTryus** [comment]
Would be great to merge this, as we have dependency in our project on this PR.

**Comment by leshakoss** [comment]
@duailibe @melonmanchan @VitaliiTryus  Thanks a lot for your contribution! I will try to release this as a part of v2.0.0-beta.1 as soon as possible (hopefully a few days). I will let you know when it’s released.

**Comment by melonmanchan** [comment]
@leshakoss any ETA on this? No rush, maintaining FOSS projects is a thankless job for the most part. 🙂

**Comment by sandrocsimas** [comment]
This is working?

**Comment by Lakston** [comment]
The API has changed since the locale was merged so it needs to be updated to match the new API. There is a list in the master branch called `outdatedLocales.json` (see [here](https://github.com/date-fns/date-fns/blob/master/outdatedLocales.json) ) and the `pt-BR` locale is listed in it.

**Pull request merged**
