### PR TITLE
Add Khmer(km) Locale Support

### LINKED ISSUE #981: Khmer language support
I have found that this library does not have Khmer language support. I am Cambodian, so I can help if you need.

### PR DESCRIPTION
**Pull request by seanghay**
Closes #981

I opened an issue a while back, but the issue was temporary closed due to I was not available to do it.  

- #981 
 
Now I am again in need of Khmer locale inside `date-fns`. And I think other people need it too.

If anything doesn't seem right, please let me know. I'll make changes to fit your needs.

Thanks!

### CODE REVIEW

**Review by tan75 — APPROVED** [review]
Thanks a lot for this PR! 🙏

**Comment by Trishanns** [comment]
Thank you and I ask you to keep my hello world going on. Thank you Patricia Collier pcollier743@gmail.com

**Comment by Kokleng-Dev** [comment]
> Closes #981
> 
> I opened an issue a while back, but the issue was temporary closed due to I was not available to do it.
> 
> * [Khmer language support #981](https://github.com/date-fns/date-fns/issues/981)
> 
> Now I am again in need of Khmer locale inside `date-fns`. And I think other people need it too.
> 
> If anything doesn't seem right, please let me know. I'll make changes to fit your needs.
> 
> Thanks!

Hello bong, i still can not get khmer language, i use version "date-fns": "^4.1.0". 
Thank you.

**Comment by seanghay** [comment]
@Kokleng-Dev share you code snippet here.

**Comment by Kokleng-Dev** [comment]
> share you code snippet here.

Here you go, Bong!
I'm using shadcn-vue in my Nuxt.js project.
```
<Calendar
          v-model="model"
          :year="selectedYear"
          :month="selectedMonth + 1"
          initial-focus
          class="p-0"
          locale="km-KH"
        />
```

I checked it — they're using date-fns.
I tested it, and it works fine with other languages, but not with Khmer.

1. france (fr-FR)
Screenshot 2025-04-07 at 1 12 12 in the afternoon

2. chinese (zh-CN)
Screenshot 2025-04-07 at 1 13 32 in the afternoon

3. thai (th-TH)
Screenshot 2025-04-07 at 1 13 52 in the afternoon

4. khmer (km-KH) not work.
Screenshot 2025-04-07 at 1 14 16 in the afternoon

**Comment by seanghay** [comment]
@Kokleng-Dev Looks like `shadcn-vue` uses `reka-ui` uses `@internationalized/date` not `date-fns`.

https://github.com/unovue/reka-ui/blob/v2/packages/core/src/date/calendar.ts#L40

**Pull request merged**
