### PR TITLE
Change ordinalNumber formatting in IT locale

### PR DESCRIPTION
**Pull request by davidspiess**
This pull request removes the º symbol from the ordinalNumber formatting function since it's primarily used to indicate the first day of the month. But leaving it away completely is also considered correct and much more common.

Example:
```js
formatDate(new Date(2020, 1, 14), "do MMMM y", itLocale)
// before 14º febbraio 2020
// after 14 febbraio 2020

```

More infos can be found here: https://en.wikipedia.org/wiki/Date_and_time_notation_in_Italy

Relevant section:
```
The expanded form is "22 dicembre 2010", optionally with the day of the week: "mercoledì 22 dicembre 2010".[1]

The first day of the month is usually written 1º dicembre or 1° dicembre; 1 dicembre is also considered correct. The other days of the month follow the usual cardinal form.
```

### CODE REVIEW

**Comment by tan75** [comment]
hi @date-fns/i18n-it 
could you please have a look into it? Is this a correct approach?

**Review by albertorestifo — APPROVED** [review]
Yep, I've never written it with the "º" in my life

**Comment by vin-car** [comment]
Yes, using the "°" for ordinal dates is quite uncommon, it has sense mostly for the first day of the month.

**Comment by fturmel** [comment]
Hope it's alright, I rebased and updated the snapshot.md file to make it easier to review and merge.

**Pull request merged**
