### PR TITLE
[i18n]: replace LT -> p, L -> P in ar, fil, ka locales

### PR DESCRIPTION
**Pull request by renton4code**
Hi awesome team!

I think there is a problem in formatting we detected in these locales.

If formatted with `LT` and `L` it gives out wrongly date, when formatted with `p` and `P`, works as expected.
Not sure why this formatting was chosen in the fist place, my suspicion is that it broke at some point.

### CODE REVIEW

**Comment by fturmel** [comment]
Can you run `yarn locale-snapshots` and commit the modified snapshot.md file(s) too?

`ar` and `fil` are the only two broken / disabled locales in the project at the moment. I think the changes to these locales won't really affect anything for now as it appears they were never fully converted from v1 to v2 format. If you are a speaker, any chance you can help make progress towards finalizing the migration?

**Comment by renton4code** [comment]
> Can you run `yarn locale-snapshots` and commit the modified snapshot.md file(s) too?
> 
> `ar` and `fil` are the only two broken / disabled locales in the project at the moment. I think the changes to these locales won't really affect anything for now as it appears they were never fully converted from v1 to v2 format. If you are a speaker, any chance you can help make progress towards finalizing the migration?

Hi @fturmel unfortunately I don't know any of those languages, I will ask around if someone can help though. Snapshot is updated!

**Comment by fturmel** [comment]
Great, that certainly seems like an improvement!

**Comment by renton4code** [comment]
> Great, that certainly seems like an improvement!

@fturmel Should we merge it then, WDYT?

**Comment by fturmel** [comment]
@renton4code Looks good, but I don't have any permissions on this repo so that part is not up to me unfortunately.

**Comment by renton4code** [comment]
@leshakoss @maximtop @tan75 Hey there, could you help with merging this?

**Comment by leshakoss** [comment]
Hi, thanks a lot for your PR! Rebased your branch into #2797

**Pull request closed without merging**
