### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by myabc**
Found (mostly) automatically with:

    codespell -S ./scripts/test/tzIANA.*,./src/intlFormat,./src/locale/[!_]*/* -L nd,te,thur
    typos --format brief --exclude "src/locale/[!_]*/*"

### CODE REVIEW

**Review by archibold — APPROVED** [review]
Good catches!

**Review by fturmel — APPROVED** [review]
Excellent!

**Review by JhonySpark — APPROVED** [review]
Nice done!

**Review by JhonySpark — APPROVED** [review]

**Comment by kossnocorp** [comment]
I appreciate it!

**Pull request merged**
