### PR TITLE
fix(typings): export interface

### PR DESCRIPTION
**Pull request by ricardogobbosouza**

### CODE REVIEW

**Comment by ricardogobbosouza** [comment]
ping @kossnocorp

**Comment by kossnocorp** [comment]
Hey! Could please explain what does it solve?

**Comment by ricardogobbosouza** [comment]
Hi @kossnocorp
I need to use the types in the nuxt module https://github.com/nuxt-community/date-fns-module.
Since it was not exported, I had to rewrite https://github.com/nuxt-community/date-fns-module/blob/master/types/index.d.ts

**Comment by kossnocorp** [comment]
Ok, I got you!

**Comment by kossnocorp** [comment]
I had to revert it ☹️, please see my PR: https://github.com/date-fns/date-fns/pull/1256#issue-298893502

**Pull request merged**
