### PR TITLE
new `defaultLocale` getter / setter

### LINKED ISSUE #816: Add function to set locale globally
Hi,

It would be great to have the possibility to call a function that set the locale globally, instead of having to wrap date-fns functions. Something similar to `moment.locale()` where we would pass the imported locale.

Thanks !

### PR DESCRIPTION
**Pull request by fturmel**
Closes #816

Dead simple getter / setter function to globally access the default locale that all functions use. No breaking changes.

This is one of the most requested features in `date-fns` by the community, hopefully this will get seriously considered. Happy to collaborate on this if the implementation doesn't fit the team's vision.

As @olee [wrote](https://github.com/date-fns/date-fns/issues/816#issuecomment-975149577), _"there is already a global state of locale - it is just that it is hardcoded to be the english locale"_.

### CODE REVIEW

**Comment by pserafini** [comment]
Implementation seems to be functional and in the spirit of date-fns. 

What's blocking your PR @fturmel ? Need more reviewers ?

**Comment by fturmel** [comment]
> What's blocking your PR @fturmel ? Need more input from the team ?

I don't have private communication channels with the maintainers, so I know as much as you do...

Maybe they have a better implementation idea that will roll out with v3? There is a task called "Set locale globally" in #2659 and an [empty i18n repo](https://github.com/date-fns/i18n), so maybe some things are in motion. I really don't understand why there has been such a lack of transparency and communication around this feature for years now. 🤷

> seems to be functional as a starting point

If you have improvement ideas, please do share.

**Comment by Webrow** [comment]
@fturmel I see some of your branches are getting merged, but this one is not, any idea if it has big blocking parts? I checked it out seems to be working fine

**Comment by tan75** [comment]
hi all, 
a PR from @kossnocorp https://github.com/date-fns/date-fns/pull/2931 will allow setting a global locale once its merged.
Its not ready yet - it doesn't cater for `options.weekStartsOn`  - now it's WIP. 
We are planning to release shortly.

**Review by matinzd — COMMENTED** [review]
`formatDistanceToNow` and `formatDistanceToNowStrict` is missing.

**Comment by leshakoss** [comment]
Or alternatively same scope but newer implementation: #3087. I'm still on edge between this and #3069

**Comment by matinzd** [comment]
> Or alternatively same scope narrow but newer implementation: #3087. I'm still on edge between this and #3069

I think both approaches are good though.

**Pull request closed without merging**
