### PR TITLE
Add yarn support

### PR DESCRIPTION
**Pull request by havenchyk**
Hey, yarn becomes more and more widely used, so let's use it and speed up at least `npm install` for a couple of seconds with `yarn`.

### CODE REVIEW

**Comment by havenchyk** [comment]
@kossnocorp what do you think, should I also change travis config in scope of this PR?

**Comment by kossnocorp** [comment]
I think we'll benefit from `lock` file 👍

**Comment by havenchyk** [comment]
@kossnocorp done, please, check again

**Comment by LeshaKoss** [comment]
@havenchyk thank you! Your changes were released with [1.19.0](https://github.com/date-fns/date-fns/releases/tag/v1.19.0) (diff: https://github.com/date-fns/date-fns/compare/v1.18.0...v1.19.0) Sorry that I forgot the changelog entry, I'll fix it with the next release 😅

**Pull request merged**
