### PR TITLE
Switch dateLeft and dateRight in intervalToDuration

### PR DESCRIPTION
**Pull request by lorenzvanherwaarden**
Functions like differenceInMonths, differenceInDays, ... , which are used in intervalToDuration, expect dateLeft to be the later date and dateRight the earlier date. Currently, intervalToDuration sets its dateLeft to its earlier date and dateRight to its later date. This has been fixed in this PR: by setting dateLeft to the end date and dateRight to the start date.

While the dateLeft and dateRight arguments can normally be switched in these functions, because they work in both cases as they use Math.abs, a sign variable, ..., meaning that it shouldn't matter in what order intervalToDuration passes dateLeft and dateRight to these functions, there are two reasons why I still think this change is useful:
- It's more logical that if the dateLeft is the later date in these 'difference' functions, this is also the case in the intervalToDuration function
- In my case, the intervalToDuration bug with Feb 28th #2255, would not have occurred if dateLeft would have been set as the later date in intervalToDuration

### CODE REVIEW

**Comment by leshakoss** [comment]
I feel like it's the differenceInX arguments that are named incorrectly, they should be something like `dateMinuend` and `dateSubtrahend`. Or just `laterDate` and `earlierDate`

**Comment by lorenzvanherwaarden** [comment]
@leshakoss I agree, using laterDate and earlierDate is more logical. I can adapt the PR if needed. I just tackled it this way because there are many differenceInX functions and I thought that was done on purpose and the error was in the intervalToDuration function.

**Review by tan75 — DISMISSED** [review]
Thank you!

**Comment by tan75** [comment]
@lorenzvanherwaarden 
unfortunately we can not accept this PR right now as this will introduce a breaking change. 
However we might re-visit this in future.
@leshakoss what do you think?

**Comment by tan75** [comment]
@kossnocorp I looked into this PR and I think it makes sense. Even if we swap the end date and the start date, it will produce a correct result as it applies the `sign` during the computation process: 
`const sign = compareAsc(dateLeft, dateRight)`

**Pull request closed without merging**
