### PR TITLE
Add Turkmen (tk) locale

### PR DESCRIPTION
**Pull request by aaabdyrahmanov**
# PR Checklist
------------
### To maintain `date-fns` top quality, please check if PR fulfills the main contributing requirements:
[x] PR follows style guides specified on the guideline:  [Contributing Guide](https://github.com/date-fns/date-fns/blob/master/CONTRIBUTING.md)
[x] Tests for the changes have been added (for bug fixes / features)
[x] Docs have been added / updated (for bug fixes / features)
[ ] Any changes made on the changelog.
[ ] Any changes made on the library version.
[x] Prior to sending pull request FP functions, typings and indices were rebuilt.
 
#### What is the new behavior?
With this PR, [date-fns](https://date-fns.org) will start to support Turkmen (tk) language.

#### Does this PR introduce a breaking change?
    * [ ] Yes
    * [x] No

### CODE REVIEW

**Review by rikkalo — CHANGES_REQUESTED** [review]
Thanks for your contribution!:+1: Note please that the module cannot have multiple default exports.
https://travis-ci.org/github/date-fns/date-fns/jobs/758914464
image

**Comment by aaabdyrahmanov** [comment]
Hey, @rikkalo thanks for the feedback! ✨ 

As you requested, I have made necessary changes to fix the issue.

**Comment by aaabdyrahmanov** [comment]
Hey @rikkalo, thanks for the feedback! ✨

As you requested, I have made necessary changes to fix the issue.

**Comment by rikkalo** [comment]
> Hey @rikkalo, thanks for the feedback! ✨
> 
> As you requested, I have made necessary changes to fix the issue.
Thank you. 


> Hey @rikkalo, thanks for the feedback! ✨
> 
> As you requested, I have made necessary changes to fix the issue.

Thanks, it looks good. Сould you please update the branch?

**Comment by aaabdyrahmanov** [comment]
> Thanks, it looks good. Сould you please update the branch?

Hey @rikkalo, I've checked it and seems the current branch is up to date.

**Pull request closed without merging**
