### PR TITLE
Added date range overlap check methods

### LINKED ISSUE #319: Method suggestion: Return the number of days that overlap in two date ranges
I had to write a method for returning the number of overlapping days in date ranges several times in different projects already and always found it a missing feature from the existing libraries.

Would you consider adding it to date-fns?

I can submit a PR with it if you're interested.

### PR DESCRIPTION
**Pull request by asia-t**
Added date range methods to determine whether and by how many days two date ranges overlap.

Resolves #319

### CODE REVIEW

**Comment by LeshaKoss** [comment]
@asia-t Hello! Thank you for your contribution!

I feel like names of these function aren't really consistent with the other functions. `isOverlappingRange` should probably be more naturally named as `isRangeOverlapping`. Also I am not sure if `num` should be shortened like this in `getNumOverlappingDays`. Maybe `getNumberOfOverlappingDays`? Or `getOverlappingDays` or `getOverlappingDaysInRange`? (we didn't use `number` at all in `getDaysInYear`, `getDaysInMonth` and `getISOWeeksInYear`) Your thoughts?

**Comment by asia-t** [comment]
@LeshaKoss Hi! Yeah, I was struggling with the naming a bit. I like your suggestions - `isRangeOverlapping` and `getOverlappingDaysInRange` sound more natural. I'll make the changed today. Thanks!

**Comment by LeshaKoss** [comment]
@asia-t also, I am not sure about it, but maybe `areRangesOverlapping` is better than `isRangeOverlapping`? There are two ranges after all

**Comment by asia-t** [comment]
Hey @LeshaKoss ! I went for plural in both for consistency's sake. So, it's now `areRangesOverlapping` and `getOverlappingDaysInRanges`. Does it sound ok?

**Comment by LeshaKoss** [comment]
@asia-t yeah, it's good! Thank you!

**Comment by LeshaKoss** [comment]
@asia-t thank you for your contribution! ⭐️ Your functions were released as [1.20.0](https://github.com/date-fns/date-fns/releases/tag/v1.20.0) (diff: https://github.com/date-fns/date-fns/compare/v1.19.0...v1.20.0)

**Comment by asia-t** [comment]
Hey @LeshaKoss ! Something is not quite right with the function `getOverlappingDaysInRanges` in the documentation on the site. It looks like I messed up the format by putting a const between the doc part and the function name :/ Sorry about that.

If that is the case, I submitted a PR that fixes it:
https://github.com/date-fns/date-fns/pull/337

**Pull request merged**
