### PR TITLE
[CS] Long time formats for Czech do not include number of hours

### LINKED ISSUE #2921: Long time formats for Czech do not include number of hours
Hello,

it seems that the definition of long time formats for the Czech language (in https://github.com/date-fns/date-fns/blob/master/src/locale/cs/_lib/formatLong/index.ts#L11) uses `H` instead of `HH` unlike other locales. This then results in weird behavior when switching between languages because strings like `1 hours 15 minutes` change to `hour 15 minutes` (in Czech).

This behaviour was encountered in [jellyfin-vue](https://github.com/jellyfin/jellyfin-vue) that uses date-fns 2.28.0 (https://github.com/jellyfin/jellyfin-vue/blob/master/package.json#L46).

### PR DESCRIPTION
**Pull request by TheKvikk**
Resolves #2921

Standardizes Czech number formats

- Added "1" to all keys containing translation for one of something – one hour, one minute etc.

### CODE REVIEW

**Review by dravecky — APPROVED** [review]

**Review by kvetis — APPROVED** [review]
I'm a Czech native speaker and this is correct.

**Review by dravecky — APPROVED** [review]

**Comment by lhotamir** [comment]
Is there any way I can help with this PR being accepted? Our users keep reporting it and we really want ot solve this

**Comment by TheKvikk** [comment]
@kossnocorp tests should be fixed

**Comment by kossnocorp** [comment]
@TheKvikk thank you a lot!

**Comment by kossnocorp** [comment]
Shipped with v3.3.0: https://github.com/date-fns/date-fns/releases/tag/v3.3.0

**Pull request merged**
