### PR TITLE
Migrate from standard to prettier

### PR DESCRIPTION
**Pull request by TrySound**
In respond to https://github.com/date-fns/date-fns/issues/753

This configuration fits the best to previous codestyle.

Also added lint-staged which should be run with pre commit hook, but
`husky` right now validates package version and fails because of your
"don't touch this". `pre-commit` just doesn't work for me. Not sure
why.

I suggest to merge now and add pre commit hook later when husky will
accept my PR.

https://github.com/typicode/husky/pull/294

### CODE REVIEW

**Comment by TrySound** [comment]
If you want I could split this PR in chunks. Let me what which ones.

**Comment by TrySound** [comment]
Done

**Comment by TrySound** [comment]
Husky is fixed. I added it and rebased.

**Comment by TrySound** [comment]
Does this look good?

**Comment by kossnocorp** [comment]
@TrySound yeah, this is great, I'm going to merge it.

**Comment by kossnocorp** [comment]
I've merged your changes with https://github.com/date-fns/date-fns/pull/756. Thank you!

**Pull request closed without merging**
