### PR TITLE
Fix the format of zeros in formatDuration in Czech locale

### PR DESCRIPTION
**Pull request by janziemba**
0 minuty -> 0 minut
0 hodiny -> 0 hodin
0 dny -> 0 dnů
0 měsíce -> 0 měsíců
0 roky -> 0 roků

### CODE REVIEW

**Review by janmyler — COMMENTED** [review]
Nice fix! Haven't noticed this one.

**Comment by tan75** [comment]
hi @janziemba 
could you please run `yarn locale-snapshots` and commit the results?
This will help the tests to run through successfully.

**Review by tan75 — CHANGES_REQUESTED** [review]
Thank you for this PR!  👍
Please run `yarn locale-snapshots` and commit the results.

**Comment by janziemba** [comment]
@tan75 Done 🙂

**Review by leshakoss — APPROVED** [review]
Thanks!

**Pull request merged**
