### PR TITLE
Fix uk locale abbreviated months matcher

### PR DESCRIPTION
**Pull request by vadimpopa**
Fix uk locale abbreviated months matcher. Extend formatParserTokens testing with all year months.
The initial abbreviations were resulting many Invalid Dates and Errors, you can see here: https://github.com/date-fns/date-fns/pull/3139/commits/371638c53e8a4f3087b5f019f54de20281755f71#diff-e7a044747c760242f5fc578749d6b8ad313008832a49188cc711ce34b77ae5d9

### CODE REVIEW

**Comment by vadimpopa** [comment]
@leshakoss Is there any way to speed up reviewing and fixing the locale issues ? There are many issues raised on several locales due to format -> parse tokens. Issues that we would like to resolve sooner than later, for our next release that's on hold because of them. I'm trying to help as I can, with your guidance of course, but I don't see much activity on them. I asked my manager to donate as well for this library as it is a core dependency of our product.

**Comment by leshakoss** [comment]
@vadimpopa hi, could you please change the base branch for this PR from `main` to `v2` and then rebase? I want to ship this as a patch

**Comment by vadimpopa** [comment]
@leshakoss all good now ?

**Review by leshakoss — APPROVED** [review]
Yep, thanks a lot!

**Comment by vadimpopa** [comment]
@leshakoss I see some failing checks due to a snapshot conflict. Anything to do about it ?

```
Error: The snapshot on the disk doesn't match the generated snapshot: /home/runner/work/date-fns/date-fns/src/locale/af/snapshot.md. Please run yarn locale-snapshots and commit the results.
[38](https://github.com/date-fns/date-fns/runs/7787400828?check_suite_focus=true#step:8:39)
    at /home/runner/work/date-fns/date-fns/scripts/build/localeSnapshots/index.js:59:21
[39](https://github.com/date-fns/date-fns/runs/7787400828?check_suite_focus=true#step:8:40)
    at async Promise.all (index 0)
```

**Comment by leshakoss** [comment]
Released this as v2.29.2: https://github.com/date-fns/date-fns/releases/tag/v2.29.2 Thanks for your contribution!

**Pull request merged**
