### PR TITLE
Min/Max accepts array instead of spread arguments (resolves #266)

### LINKED ISSUE #266: Make `min` and `max` accept arrays instead of spread arguments
It will help with consistency and FP functions.

### PR DESCRIPTION
**Pull request by mihirk**

### CODE REVIEW

**Comment by mihirk** [comment]
This is an alternative, if you like this one better I can finalise this as well - 
https://github.com/mihirk/date-fns/tree/helper

**Comment by LeshaKoss** [comment]
@mihirk thank you! It is a breaking change, so we have to wait for 2.0.0 though 😬

**Comment by kossnocorp** [comment]
@mihirk thank you 💪  We'll release it as soon as `2.0` [is ready](https://github.com/date-fns/date-fns/issues?q=is%3Aopen+is%3Aissue+milestone%3Av2.0.0).

**Comment by LeshaKoss** [comment]
@mihirk Hello, we created a branch for v2: https://github.com/date-fns/date-fns/tree/v2 Could you please resend your PR there? Thanks

**Comment by kossnocorp** [comment]
I'm reopening this PR to `v2` branch

**Comment by kossnocorp** [comment]
Please continue here: https://github.com/date-fns/date-fns/pull/333

**Pull request closed without merging**
