### PR TITLE
parse → toDate & new parse function (closes #219)

### LINKED ISSUE #219: Add an ability to pass the format to parse function, so it would be possible to parse dates in any format
Thank you for the nice library!

I was going to use this library, but figured out that it is not possible to parse data by arbitary format. I'd like to do the following

``` js
var dateString = '10.02.1999'
var date = parse(dateString, 'DD.MM.YYYY')
```

[`format`](https://date-fns.org/docs/format) function is already has set of tokens, which can also be used for parsing.

[Moment also has the same feature](http://momentjs.com/docs/#/parsing/string-format/), so it is reasonable to have it there as well.

I can try to implement this and send a PR if you approve general idea of this feature.

### PR DESCRIPTION
**Pull request by leshakoss**

### CODE REVIEW

**Comment by leshakoss** [comment]
@kossnocorp please review

**Comment by fxck** [comment]
Any idea when is this gonna be released?

**Comment by leshakoss** [comment]
@fxck probably this month

**Comment by fxck** [comment]
Alright, cool, are you keeping builds / @next releases somewhere by any chance?

**Comment by kossnocorp** [comment]
@fxck not yet, but alpha is coming really soon.

**Comment by fxck** [comment]
Sorry to bother you again, but is that alpha anywhere near? I would help a ton. Thank you, thank you.

**Comment by kossnocorp** [comment]
It is. We can provide you with an alpha, but the API could change as we are settling up some details ATM, so I'm not sure if it's a good idea. Which locales you use (if any)?

**Comment by fxck** [comment]
I don't mind a slightest bit if the API changes. Just Czech locale at the moment.

**Pull request merged**
