### PR TITLE
Fix cjs and typings pathes in package.json

### PR DESCRIPTION
**Pull request by goloveychuk**
Mb declarations was correct before. Please correct me.

### CODE REVIEW

**Comment by rkovalyov** [comment]
👍

**Comment by kossnocorp** [comment]
Could you please explain what problem you tried to solve here?

**Comment by rkovalyov** [comment]
@kossnocorp `main` property in package.json should link with cjs, not esm module, it our case jest try to resolve esm module and failed

**Comment by kossnocorp** [comment]
Do you mean the root `package.json`? `main` there links to the CommonJS and `module` to ESM. `package.json` files in functions don't have `main` property at all.

**Comment by kossnocorp** [comment]
I closing this PR but will be happy to merge it once I understand the problem and have problem reproduction steps or even better a repo.

**Pull request closed without merging**
