### PR TITLE
Add ko locale

### PR DESCRIPTION
**Pull request by iamssen**
😀

### CODE REVIEW

**Comment by KunHwanAhn** [comment]
Thank you for your effort. I like this PR!

What do you think about adding `i18n` label on this PR to be exposed to committers easy like https://github.com/date-fns/date-fns/pull/1090?

**Comment by iamssen** [comment]
image

@KunHwanAhn I do not think I have permission to edit the labels. Can I add a label?

**Comment by KunHwanAhn** [comment]
I thought that you can add the label because you are the owner of this PR 😭

Thank you for checking about this.

We have to wait a response from the committers.

**Comment by KunHwanAhn** [comment]
Hi, @mareksuscak. 

The reason why I mentioned you is that I think person who is not either a member or contributor don't have a permission to add the label.

I'd like to add `i18n` label on this PR like #1090 to be exposed to contributor easy and handled by them. Can I ask it to you?

**Comment by zirho** [comment]
Is this WIP or ready to be merged?

**Comment by kossnocorp** [comment]
I've released the change as `v2.0.0-alpha.29`: https://gist.github.com/kossnocorp/a307a464760b405bb78ef5020a4ab136#v200-alpha29

**Pull request merged**
