### PR TITLE
Fix eachHourOfInterval example dates

### PR DESCRIPTION
**Pull request by CarlRosell**
The dates in the example did not match the example output

### CODE REVIEW

**Comment by tan75** [comment]
Hello @CarlRosell 

Thank you for this PR!
Could you please resolve the conflicts and update snapshots by running `yarn locale-snapshots` ?

**Comment by CarlRosell** [comment]
The merge commit triggered prettier to run on all stages files, that's why this PR says 13 changed files. Do you want me to create a new PR or are the prettier changes ok to keep?

**Comment by CarlRosell** [comment]
Nevermind, I rebased everything and just added the change that was intended.

**Review by tan75 — APPROVED** [review]
Thank you!

**Pull request merged**
