### PR TITLE
Improved German and fr-CH formatLong

### PR DESCRIPTION
**Pull request by vanvuongngo**
formatLong L for German and fr-CH

### CODE REVIEW

**Comment by kossnocorp** [comment]
Please tell me you need help with the PR.

**Comment by vanvuongngo** [comment]
@kossnocorp You can continue the PR. I do not know the actual alpha state.

**Comment by kossnocorp** [comment]
@vanvuongngo what do you mean? I still see some `describe.skip` in the code. I would love to release a new alpha with your changes once it's done.

**Comment by vanvuongngo** [comment]
@kossnocorp To remove the describe.skip it needs translations

**Comment by kossnocorp** [comment]
I see. So you're have no plans to continue work on the PR?

I'm afraid that I can't continue working on it as I don't understand German. I can help only with code and guidance.

**Comment by vanvuongngo** [comment]
@kossnocorp Glad to here you want to integrate my change. I had a look at the translation and removed the skips.

**Comment by kossnocorp** [comment]
Thank you a lot! It was released as `v2.0.0-alpha.7`. See change log: https://gist.github.com/kossnocorp/a307a464760b405bb78ef5020a4ab136#v200-alpha7

**Pull request merged**
