### PR TITLE
$ chmod -x CHANGELOG.md

### PR DESCRIPTION
**Pull request by tricknotes**
This file doesn't need executive permission.

### CODE REVIEW

**Comment by dkozickis** [comment]
Why not 666?

**Comment by tricknotes** [comment]
I think the minimum permission is good practice.
Also, many files in date-fns seem to have 644 permission.

**Comment by dkozickis** [comment]
Thanks, this one is a nice reference too - https://www.redhat.com/sysadmin/introduction-chmod

**Comment by kossnocorp** [comment]
Thanks!

**Pull request merged**
