### PR TITLE
Experimental Moment API

### PR DESCRIPTION
**Pull request by kossnocorp**
Made it for lulz first but then realized that it's possible to achieve.

### CODE REVIEW

**Comment by kossnocorp** [comment]
Please left a comment if you're interested.

**Comment by RIanDeLaCruz** [comment]
@kossnocorp Was wondering what this is exactly doing? Creating an API that mirrors the API of moment?

**Comment by kossnocorp** [comment]
@RIanDeLaCruz exactly

**Comment by RIanDeLaCruz** [comment]
@kossnocorp I'm mildly interested. What do you think would be the benefit of doing this?

**Comment by kossnocorp** [comment]
@RIanDeLaCruz I thought that it would encourage people to migrate from Moment and help to identify the subtle differences between similar functions.

Closing it as I doubt that I'll have enough time and focus for that.

**Pull request closed without merging**
