### PR TITLE
Add ht locale.

### PR DESCRIPTION
**Pull request by rmariuzzo**
This PR add locale data for “Haitian Creole” (ht/hta).

### CODE REVIEW

**Comment by rmariuzzo** [comment]
What should we do the next? How can I help?

**Comment by tan75** [comment]
> What should we do the next? How can I help?

hi @rmariuzzo 
Thank you so much for your contribution! 
Please allow us some time to review your PR and we will get back to you!

**Comment by rmariuzzo** [comment]
Perfect! Let me know how I can help.

**Review by tan75 — APPROVED** [review]
Thank you!

**Comment by kossnocorp** [comment]
Thank you a lot!

**Comment by rmariuzzo** [comment]
Thank you for the followup.

**Pull request merged**
