### PR TITLE
Add JA locale (closes #240)

### LINKED ISSUE #240: Japanese language support

### PR DESCRIPTION
**Pull request by DeMuu**
added JP translations + updated tests

#240

### CODE REVIEW

**Comment by LeshaKoss** [comment]
Hello @DeMuu! Thank you for your awesome contribution! But isn't the code for Japanese language is `ja`, not `jp`?

**Comment by DeMuu** [comment]
indeed. I am so used to referring to it as JP due to the JPN abbrevation (which is the long code version). fixed it '^-^

**Comment by LeshaKoss** [comment]
@DeMuu you forgot the locale directory name 😅

**Comment by DeMuu** [comment]
😞 

fixed. as GitHub was down I couldn't upload it any sooner^^

**Comment by LeshaKoss** [comment]
@DeMuu forgot to mention, the Japanese locale was released with [1.8.0](https://github.com/date-fns/date-fns/releases/tag/v1.8.0). (diff: https://github.com/date-fns/date-fns/compare/v1.7.0...v1.8.0) Thank you for your awesome contribution!

**Pull request merged**
