### PR TITLE
Add ar-MA locale support

### PR DESCRIPTION
**Pull request by rramiachraf**
I've just added the ar-MA support

### CODE REVIEW

**Comment by kossnocorp** [comment]
Hey, thank you a lot for your work!

You can see that tests fail on the CI; you need to run `yarn locale-snapshots` and commit the result. Thanks!

**Comment by rramiachraf** [comment]
@kossnocorp I actually did that, you can see the file on the `Files Changed` tab.
I don't know why the test has failed.

**Comment by kossnocorp** [comment]
Maybe you've changed something after you built it. If it's not a case, I'll take a look myself.

**Comment by rramiachraf** [comment]
@kossnocorp Not really! i didn't change any of the files, it would much appreciated if you could take a look.

**Pull request merged**
