### PR TITLE
Add typescript typings

### PR DESCRIPTION
**Pull request by mattlewis92**
I originally wrote these and published them to definitely typed, but it would probably be easier to just have them bundled with the library itself. Let me know what you think! (filename and location could do with bikeshedding)

### CODE REVIEW

**Comment by kossnocorp** [comment]
Lovely! Thank you for your work!

@LeshaKoss please publish a new version with this goodness!

**Comment by mattlewis92** [comment]
Brilliant, thanks for accepting! 😀

**Comment by LeshaKoss** [comment]
@mattlewis92 TypeScript typings were released with [1.11.0](https://github.com/date-fns/date-fns/releases/tag/v1.11.0). (diff: https://github.com/date-fns/date-fns/compare/v1.10.0...v1.11.0) Thank you for your contribution! 🏅

**Comment by mattlewis92** [comment]
Awesome, thanks for the quick response! :)

Kind regards,
Matt Lewis

**Pull request merged**
