### PR TITLE
Fix types break on typescript 2.5.3 for master branch

### PR DESCRIPTION
**Pull request by plantain-00**
#572

### CODE REVIEW

**Comment by artem-malko** [comment]
:+1:

**Comment by artem-malko** [comment]
@kossnocorp @leshakoss your review is required!)

**Comment by bbenezech** [comment]
Can someone blind-merge it? At worst TS users like me will come back and say what's what. It's just dumb d.ts files and a non-core script. We can't end worst than current's situation. Same for #598

**Comment by leshakoss** [comment]
Sorry, missed it

**Comment by bbenezech** [comment]
Thanks a lot @leshakoss. I'll test it as soon as a new release is cut.

**Comment by leshakoss** [comment]
@bbenezech we need to wait for @kossnocorp to release it. Meanwhile, you can test it by building a package with this trick:
```
env PACKAGE_OUTPUT_PATH="$(pwd)/../PATH-TO-YOUR-MODULE/node_modules/date-fns" ./scripts/build/package.sh
```

**Pull request merged**
