### PR TITLE
export each key seperately along with complete local export  in en-us #1468

### PR DESCRIPTION
**Pull request by aravind1078**

### CODE REVIEW

**Comment by kossnocorp** [comment]
Unfortunately, it's a breaking change that we can't accept right now. Please tell more about why do you need it, and we'll consider it for the next version if it makes sense.

**Comment by WarisR** [comment]
@kossnocorp 
Now when I need to use locale object for formatRelative translation I do as below
```javascript
import { subDays, formatRelative } from 'date-fns';
import enUs from 'date-fns/locale/en-US'

return formatRelative(subDays(new Date(), 3), new Date(), { locale: enUs })
```

But enUs locale object has too many functionalities than what we need.
So I have to import this big bundle, but what I need is only formatRelative.
That make my js bundle bigger by import unused code.
```javascript
var locale = {
  formatDistance: formatDistance,
  formatLong: formatLong,
  formatRelative: formatRelative,
  localize: localize,
  match: match,
  options: {
    weekStartsOn: 0 /* Sunday */,
    firstWeekContainsDate: 1
  }
};
```

Could you please provide a way to get only formatRelative from the locale object as below?
```javascript
import { subDays, formatRelative } from 'date-fns';
import { formatRelative as enFormatRelative } from 'date-fns/locale/en-US'

return formatRelative(
  subDays(new Date(), 3),
  new Date(),
  { locale: { formatRelative: enFormatRelative  }
)
```

**Comment by kossnocorp** [comment]
Thank you for your input, that makes sense, but we can't accept the PR as is. 

It will require changes across the board (update all locales and pending PRs, update docs, work with the community). 

If you want to champion the change, I'll be glad to offer guidance. Otherwise, I can't tell you when we'll get there as right now we have other priorities (time zones support).

**Comment by kossnocorp** [comment]
Right now, you can simply copy-paste locales into your source code and apply the change there.

**Comment by aravind1078** [comment]
@kossnocorp as @WarisR explained it was meant to solve #1468 . But I thought it was meant only for en-us.

**Pull request closed without merging**
