### PR TITLE
Adjust Flemish short date format

### PR DESCRIPTION
**Pull request by call-a3**
As per the recommendation of the flemish government, documented at https://www.vlaanderen.be/taaladvies/datumnotatie

### CODE REVIEW

**Comment by tan75** [comment]
Hello @date-fns/i18n-nl-be 
could you please double-check and approve this PR? 
Many thanks!

**Comment by DCBN** [comment]
The change checks out to me, just fix the failing tests and I'll approve.

**Comment by tan75** [comment]
> The change checks out to me, just fix the failing tests and I'll approve.

The tests have been fixed. Please approve this PR.

**Review by tan75 — APPROVED** [review]
Thank you! 👍

**Review by DCBN — APPROVED** [review]
Looks good, well done!

**Pull request merged**
