### PR TITLE
Add new feature addBusinessDays

### PR DESCRIPTION
**Pull request by ThorrStevens**
Should partly solve [#584](https://github.com/date-fns/date-fns/issues/584). Allthough it does not take holidays into consideration, I recon it might still have some value for end users.

### CODE REVIEW

**Comment by ThorrStevens** [comment]
PS: Also planning on making a PR for a `getWeekDays` function somewhere in the near future.

This is how I've solved the lack thereof so far:

```javascript
// Get a range or number of weekdays
export const weekDays = (start: DirtyDateType, end: DirtyDateType, asNumber: boolean = false) => {
    if (!start || !end) return 0;
    const businessDays = eachDay(toDate(start), toDate(end)).filter(d => !isWeekend(d));
    return asNumber ? businessDays.length : businessDays;
};
```

Is a function like this something that could be handy in your opinion?

**Comment by kossnocorp** [comment]
Update: I've figured that "business day" is more common term, so please name it `addBusinessDays`.

**Comment by ThorrStevens** [comment]
> Update: I've figured that "business day" is more common term, so please name it `addBusinessDays`.

Updated to `addBusinessDays` as requested 🙌

**Comment by kossnocorp** [comment]
Thanks for the update! I see that the tests fail in `America/Santiago` time zone: https://travis-ci.org/date-fns/date-fns/jobs/543469770#L691

The problem that your tests operate on the DST edge (which is a lucky coincidence) and it causes an hour shift. Look how `eachDayOfInterval` solves this problem: https://github.com/date-fns/date-fns/blob/master/src/eachDayOfInterval/index.js#L94. However, in your case, instead of setting time to 00:00, you have to save hours and reapply in each iteration. I think this will work.

Since your function, is affected by DST, please add a DST test. See:

- https://github.com/date-fns/date-fns/blob/master/scripts/test/dst.sh
- https://github.com/date-fns/date-fns/blob/master/test/dst/eachDayOfInterval/basic.js

Also, please rebase your branch with the fresh master.

Please tell me if you need assistance!

**Comment by ThorrStevens** [comment]
I'm not 100% sure I follow.
I get that the DST is giving problems in some regions, but I'm still unsure of how to fix it.

More specifically, I'm unsure of:
- How to "save" hours in the function
- If I should move the failing test from `./src/addBusinessDays/test.js` to `./test/dst/addBusinessDays/basic.js`

PS: I'll likely only have time to get back to this in a few days.
Any help would be appreciated though.

**Comment by kossnocorp** [comment]
Alrighty, I'll proceed from here 👌

**Comment by kossnocorp** [comment]
You can see the solution for the DST problem: https://github.com/date-fns/date-fns/pull/1154/commits/03bbf4d3609bfe58d038df8e5ba6307e91c8c90c

**Comment by kossnocorp** [comment]
This PR was released as `v2.0.0-alpha.32`: https://gist.github.com/kossnocorp/a307a464760b405bb78ef5020a4ab136#v200-alpha32

**Comment by ThorrStevens** [comment]
Thanks a bunch for the help and finalisation! 🙌 I’ll try to take some time this weekend to check out how the final pieces actually connect with fixing the tests

**Comment by hugows** [comment]
Its very unexpected that this function doesn't accept negative arguments.

**Pull request merged**
