### PR TITLE
fix: extra punctuation in DE medium date

### PR DESCRIPTION
**Pull request by pmmmwh**
Since #2365 added punctuation in the abbreviated forms of German months, the . in the medium format to display abbreviated months is no longer needed and if kept would yield Invalid Dates.

### CODE REVIEW

**Review by tan75 — CHANGES_REQUESTED** [review]
hi @pmmmwh 
thank you for this PR! 👍 
Could you please run `yarn locale-snapshots` and commit the results? This will help the tests to pass.

**Comment by tan75** [comment]
hi @date-fns/i18n-de 
could you please have a look and review this PR?

**Review by saithis — APPROVED** [review]

**Comment by pmmmwh** [comment]
Updated locale snapshots! There are still some instances of `Invalid Date` that I can see but I think they are unrelated to this. I think tests should pass now.

**Comment by tan75** [comment]
@saithis 
thank you!

**Review by tan75 — APPROVED** [review]
Thank you for your PR! 👍

**Pull request merged**
