### PR TITLE
Fix russian locale parsing issue

### PR DESCRIPTION
**Pull request by davidgape89**
This fixes a bug in the Russian locale date parsing. When the abbreviation of the month ends with a period, the parsing fails and returns an invalid date. I just added that trailing optional period at the end of the months.
Here's a reproduction of the problem: https://stackblitz.com/edit/js-hv7vda?file=index.js

If I try to generate the typings, I get changes in 697 files, but I haven't seen that in other PRs, especially for such a small change as mine. Should I still generate them?

### CODE REVIEW

**Review by MickMonaghan — APPROVED** [review]
LGTM

**Review by kossnocorp — APPROVED** [review]
Thank you!

**Comment by arnif** [comment]
Great fix! Any chance we could get this to master ?

**Comment by kossnocorp** [comment]
Merging it and shipping soon, thank you, everyone!

**Pull request merged**
