### PR TITLE
[refacto] renamed format to formatDate

### PR DESCRIPTION
**Pull request by Lakston**
WIP of #776

I chose to do only one at a time since I don't really know if what I did actually works and if what I did made sense. Basically I renamed all the occurrences of the `format` function to `formatDate` except in the build generated files.

I would have liked to be able to run the build script so I could check that the generated files reflect the renaming of the format function and so I could run the tests (I get an error because the fp files refer to a folder that does not exists anymore), how can I do that locally ?

No worries if that's not the right approach and it get scrapped, I learned to use rebase in the process so it's still a win for me !

### CODE REVIEW

**Comment by leshakoss** [comment]
Sorry for not responding to you in that issue.

That is not the right approach :-) The plan was to make an alias, not fully rename the function, which would mean that the function is accessible by both names in any way.

**Comment by Lakston** [comment]
Hey no worries, I was thinking that would be waaaay better, but would you do that in the build script so it creates 2 exports then ?

I wasn't sure modifying the build script to include something that specific was the right approach either.

**Comment by leshakoss** [comment]
@Lakston I think that the function also should be accessible by `import ... from 'date-fns/formatDate'` for consistency, it should be searchable in the docs (and the docs should contain a note that it is an alias to what), and it has to be tested (at least some basic regular test + 2 FP tests: for `formatDate` and `formatDateWithOptions`). I am actually not sure what exact implementation would be the best in these case: either generating the whole functionality about the function during the build process, or treating it as a regular function (with content `import format from '../format'; export default format`), and doing a special case only for the documentation.

**Comment by Lakston** [comment]
I'll see if I can come up with something, I'll close this PR in the mean time, thanks for your input !

**Pull request closed without merging**
